
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.5.13-7-MANJARO - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1102 (message)"
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2023 NVIDIA Corporation
      Built on Fri_Nov__3_17:16:49_PDT_2023
      Cuda compilation tools, release 12.3, V12.3.103
      Build cuda_12.3.r12.3/compiler.33492891_0
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1102 (message)"
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2023 NVIDIA Corporation
      Built on Fri_Nov__3_17:16:49_PDT_2023
      Cuda compilation tools, release 12.3, V12.3.103
      Build cuda_12.3.r12.3/compiler.33492891_0
...
